

- name: Creating a download directory for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{prometheus_configuration_directory}}"
    - "{{ prometheus_archive_file_download_dir}}"


- name: downloding prometheus archeive file
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "{{ prometheus_archive_file_download_dir }}"
    owner: root
    group: root

- name: extracting the file from zip
  unarchive:
    src: "{{prometheus_archive_file_download_dir}}/{{prometheus_download_zip}}"
    dest: "{{prometheus_archive_file_download_dir}}"
    owner: root
    group: root
    remote_src: yes

- name: copying the file to user/local/bin
  copy:
    src: "{{prometheus_archive_file_download_dir}}/{{ prometheus_folder_name }}/{{prometheus_binary}}"
    dest: "{{prometheus_binary_location}}/{{prometheus_binary}}"
    owner: root
    group: root
    mode: 111
    remote_src: yes


- name: copying the prometheus conf file from our local file location
  copy:
    src:  "config/prometheus.yml"
    dest: "{{prometheus_configuration_directory}}/prometheus.yml"
    owner: root
    group: root
  notify:
    - service restart prometheaus


- name: copying the systemd file for location
  template:
    src: "systemd/system/prometheus.service.j2"
    dest: "/etc/systemd/system/{{prometheus_service_name}}.service"
    owner: root
    group: root
  notify:
    - systemd Deamon reload

#after adding the service file the status will be inactive, so to activate that use as below

- name: start and enable the prometheus service
  service:
    name: "{{prometheus_service_name}}"
    enabled: true
    state: started